<?php
// $Id$

/**
 * @file
 * Implements signup statuses
 */

//////////////////////////////////////////////////////////////////////////////

define('SIGNUP_STATUS_MANAGE_PERMISSION', 'manage signup status codes');

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implementation of hook_init().
 */
function signup_status_init() {
  foreach (signup_status_codes() as $cid => $code) {
    eval('
      function signup_status_change_status_to_'. $cid .'($signup) {
        $cid = '. $cid .';
        $codes = signup_status_codes();
        db_query("UPDATE {signup_log} SET status = %d WHERE sid = %d", $cid, $signup->sid);
        watchdog(\'action\', "Set status of %signup_label to %status_name.", array(\'%signup_label\' => $signup->label, \'%status_name\' => $codes[$cid][\'name\']));
      }
   ');
  }
}

/**
 * Implementation of hook_perm().
 */
function signup_status_perm() {
  return array(SIGNUP_STATUS_MANAGE_PERMISSION);
}

/**
 * Implementation of hook_menu().
 */
function signup_status_menu() {
  return array(
    'admin/settings/signup_status' => array(
      'title' => 'Signup status',
      'description' => 'Configure signup status settings.',
      'page callback' => 'signup_status_admin_list',
      'access arguments' => array(SIGNUP_STATUS_MANAGE_PERMISSION),
      'file' => 'signup_status.admin.inc',
    ),
    'admin/settings/signup_status/list' => array(
      'title' => 'Status codes',
      'type' => MENU_DEFAULT_LOCAL_TASK,
    ),
    'admin/settings/signup_status/add' => array(
      'title' => 'Add status code',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('signup_status_admin_form', 3),
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
      'access arguments' => array(SIGNUP_STATUS_MANAGE_PERMISSION),
      'file' => 'signup_status.admin.inc',
    ),
    'admin/settings/signup_status/edit' => array(
      'title' => 'Configure status code',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('signup_status_admin_form', 3, 4),
      'type' => MENU_CALLBACK,
      'access arguments' => array(SIGNUP_STATUS_MANAGE_PERMISSION),
      'file' => 'signup_status.admin.inc',
    ),
    'admin/settings/signup_status/delete' => array(
      'title' => 'Configure status code',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('signup_status_admin_delete', 4),
      'type' => MENU_CALLBACK,
      'access arguments' => array(SIGNUP_STATUS_MANAGE_PERMISSION),
      'file' => 'signup_status.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_action_info().
 */
function signup_status_action_info() {
  $info = array();
  foreach (signup_status_codes() as $cid => $code) {
    $info['signup_status_change_status_to_'. $cid] = array(
      'type' => 'signup',
      'description' => t('Change signup status to !status', array('!status' => $code['name'])),
      'configurable' => FALSE,
    );
  }
  return $info;
}

//////////////////////////////////////////////////////////////////////////////
// Views integration

/**
 * Implementation of hook_views_api().
 */
function signup_status_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'signup_status') .'/views',
  );
}

//////////////////////////////////////////////////////////////////////////////
// Signup form altering

/**
 * Alter the signup form to add a status selector, if available.
 */
function signup_status_form_signup_form_alter(&$form, $form_state) {
  $options = array();
  foreach (signup_status_codes() as $cid => $code) {
    if ($code['show_on_form']) {
      $options[$cid] = $code['name'];
    }
  }
  if (!empty($options)) {
    $form['collapse']['signup_status'] = array(
      '#type' => 'select',
      '#title' => t('Status'),
      '#options' => $options,
      '#weight' => 1,
    );
    $form['collapse']['submit']['#weight'] = 2;
    $form['#submit'][] = 'signup_status_alter_signup_form_submit';
  }
}

/**
 * Handles submission of the altered signup form.
 */
function signup_status_alter_signup_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  if (isset($values['signup_status'])) {
    $sql = "UPDATE {signup_log} SET status = %d WHERE uid = %d AND nid = %d";
    $args = array($values['signup_status'], $values['uid'], $values['nid']);
    if (isset($values['signup_anon_mail'])) {
      $sql .= " AND anon_mail = '%s'";
      $args[] = $values['signup_anon_mail'];
    }
    db_query($sql, $args);
  }
}

/**
 * Alter the signup edit form to add a status selector, if available.
 */
function signup_status_form_signup_edit_form_alter(&$form, $form_state) {
  $signup = $form['#signup'];
  $options = array();
  foreach (signup_status_codes() as $cid => $code) {
    if ($code['show_on_form']) {
      $options[$cid] = $code['name'];
    }
  }
  if (!empty($options)) {
    $form['elements']['signup_status'] = array(
      '#type' => 'select',
      '#title' => t('Status'),
      '#options' => $options,
      '#default_value' => $signup->status,
      '#weight' => 1,
    );
    $form['elements']['save']['#submit'][] = 'signup_status_alter_signup_edit_form_submit';
    $form['elements']['save']['#weight'] = 2;
    $form['elements']['cancel-signup']['#weight'] = 3;
  }
}

/**
 * Handles submission of the altered signup edit form.
 */
function signup_status_alter_signup_edit_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  $signup = $form['#signup'];
  if (isset($values['signup_status'])) {
    db_query("UPDATE {signup_log} SET status = %d WHERE sid = %d", $values['signup_status'], $signup->sid);
  }
}

/**
 * Alter the broadcast form to allow broadcasting to just a single status.
 */
function signup_status_form_signup_broadcast_form_alter(&$form, $form_state) {
  $options = array();
  $codes = signup_status_codes();
  $options[-1] = t('- All -');
  foreach ($codes as $cid => $code) {
    $options[$cid] = $code['name'];
  }

  $form['signup_status_codes'] = array(
    '#type' => 'select',
    '#title' => t('Limit recipients'),
    '#description' => t('Send this email to a specific set of users based on signup status.'),
    '#multiple' => TRUE,
    '#options' => $options,
    '#default_value' => -1,
  );
  $form['send']['#weight'] = 10;

  // Overwrite the submit hook, in case the user selects a specific status
  $form['#validate'][] = 'signup_status_signup_broadcast_form_validate';
  $form['#submit'] = array('signup_status_signup_broadcast_form_submit');
}

/**
 * Validate altered broadcast form.
 */
function signup_status_signup_broadcast_form_validate($form, &$form_state) {
  $codes = $form_state['values']['signup_status_codes'];
  if (!in_array(-1, $codes)) {
    $signups = signup_get_signups($form_state['values']['nid']);
    $count = 0;
    foreach ($signups as $signup) {
      if (in_array($signup->status, $codes)) {
        $count++;
      }
    }
    if (!$count) {
      form_set_error('signup_status_codes', t('No users are signed up with that status.'));
    }
  }
}

/**
 * Handles submission of the altered broadcast form.
 */
function signup_status_signup_broadcast_form_submit($form, &$form_state) {
  global $user;

  if (user_access('administer site configuration')) {
    $from = $form_state['values']['from'];
  }
  else {
    $from = $user->mail;
  }

  $signups = array();
  $codes = $form_state['values']['signup_status_codes'];
  if (!in_array(-1, $codes)) {
    foreach (signup_get_signups($form_state['values']['nid']) as $signup) {
      if (in_array($signup->status, $codes)) {
        $signups[] = $signup;
      }
    }
  }

  signup_send_broadcast($form_state['values']['nid'], $form_state['values']['subject'], $form_state['values']['message'], $from, !empty($form_state['values']['copy']), $signups);
}

/**
 * Retrieve all available status codes.
 *
 * @return
 *   An array of status code arrays, keyed using the status code id, cid.  Each status code array contains the following keys / values:
 *   - "name": The display name of the status code.
 *   - "description": The long-form description of the status code.
 *   - "mod_signup_count": A boolean value stating whether signups using the status code should modify the total signup count (i.e. for the "wait listed" status code).
 *   - "show_on_form": A boolean value stating if this status should be available on the signup form.
 */
function signup_status_codes() {
  static $codes = array();
  if (empty($codes)) {
    $result = db_query("SELECT * FROM {signup_status_codes}");
    while ($row = db_fetch_object($result)) {
      $codes[$row->cid] = array('name' => $row->name, 'description' => $row->description, 'mod_signup_count' => $row->mod_signup_count, 'show_on_form' => $row->show_on_form);
    }
  }
  return $codes;
}

